/**
 * AI Smart Dress Shop - Product Dataset & Seed Data
 * Rich realistic commercial catalog with comprehensive attributes for the AI engine
 */

const FASHION_PRODUCTS = [
  // 1. Black Modern Wedding / Party (Requested in example)
  {
    id: "PROD-101",
    name: "Midnight Silk Modern Tuxedo Shirt",
    category: "Men",
    subCategory: "Formal Wear",
    gender: "men",
    color: "Black",
    sizes: ["S", "M", "L", "XL", "XXL"],
    style: "Modern",
    occasion: "Wedding",
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
    material: "95% Mulberry Silk, 5% Elastane",
    description: "Tailored luxury satin-finish shirt with a structured band collar and French cuffs. Designed for evening receptions and black-tie wedding galas.",
    tags: ["black", "modern", "wedding", "silk", "tuxedo", "party"],
    inStock: true
  },
  {
    id: "PROD-102",
    name: "Noir Velvet Evening Cocktail Gown",
    category: "Women",
    subCategory: "Party Wear",
    gender: "women",
    color: "Black",
    sizes: ["XS", "S", "M", "L"],
    style: "Modern",
    occasion: "Party",
    price: 3899,
    originalPrice: 6999,
    rating: 4.8,
    reviewsCount: 98,
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=600&q=80",
    material: "Plush Micro-Velvet with Silk Lining",
    description: "Sculptural column gown featuring a modern asymmetric neckline and side slit. Commands attention at luxury parties and contemporary weddings.",
    tags: ["black", "modern", "party", "gown", "wedding", "velvet"],
    inStock: true
  },
  {
    id: "PROD-103",
    name: "Royal Navy Tailored Wool Blazer",
    category: "Formal Wear",
    subCategory: "Men",
    gender: "men",
    color: "Blue",
    sizes: ["M", "L", "XL", "XXL"],
    style: "Formal",
    occasion: "Office",
    price: 4599,
    originalPrice: 7999,
    rating: 4.9,
    reviewsCount: 215,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    material: "100% Superfine Merino Wool",
    description: "Double-breasted navy blazer with horn buttons and half-canvas construction. Perfect for executive boardrooms and high-stakes meetings.",
    tags: ["blue", "formal", "office", "blazer", "wool", "men"],
    inStock: true
  },
  {
    id: "PROD-104",
    name: "Crimson Anarkali Silk Ensemble",
    category: "Traditional Wear",
    subCategory: "Women",
    gender: "women",
    color: "Red",
    sizes: ["S", "M", "L", "XL"],
    style: "Traditional",
    occasion: "Festival",
    price: 4999,
    originalPrice: 8999,
    rating: 4.9,
    reviewsCount: 310,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80",
    material: "Chanderi Silk with Zari Embroidery",
    description: "Flared red celebratory festive silhouette adorned with golden gota patti needlework and matching organza dupatta.",
    tags: ["red", "traditional", "festival", "wedding", "anarkali", "silk"],
    inStock: true
  },
  {
    id: "PROD-105",
    name: "Emerald Minimalist Linen Summer Dress",
    category: "Casual Wear",
    subCategory: "Women",
    gender: "women",
    color: "Green",
    sizes: ["XS", "S", "M", "L", "XL"],
    style: "Minimal",
    occasion: "Casual",
    price: 1899,
    originalPrice: 3299,
    rating: 4.7,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=600&q=80",
    material: "100% Breathable Organic French Linen",
    description: "Effortless A-line midi dress in rich forest green with hidden pockets and an adjustable tie sash.",
    tags: ["green", "minimal", "casual", "linen", "summer", "dress"],
    inStock: true
  },
  {
    id: "PROD-106",
    name: "Pastel Rose Blossom Pleated Gown",
    category: "Party Wear",
    subCategory: "Women",
    gender: "women",
    color: "Pink",
    sizes: ["XS", "S", "M", "L"],
    style: "Modern",
    occasion: "Date",
    price: 3299,
    originalPrice: 5499,
    rating: 4.8,
    reviewsCount: 89,
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=80",
    material: "Soft Georgette with Satin Lining",
    description: "Delicate blush pink gown with sunburst accordion pleats and a flattering cinched waistline. Ideal for romantic dinners and cocktail dates.",
    tags: ["pink", "modern", "date", "party", "gown", "pleated"],
    inStock: true
  },
  {
    id: "PROD-107",
    name: "Urban Oversized Monochrome Hoodie",
    category: "Casual Wear",
    subCategory: "Men",
    gender: "men",
    color: "Black",
    sizes: ["S", "M", "L", "XL", "XXL"],
    style: "Streetwear",
    occasion: "College",
    price: 1599,
    originalPrice: 2799,
    rating: 4.6,
    reviewsCount: 164,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80",
    material: "450 GSM Heavyweight French Terry Cotton",
    description: "Relaxed drop-shoulder hoodie with ribbed cuffs and subtle tonal silicone branding. The ultimate campus staple.",
    tags: ["black", "streetwear", "college", "casual", "hoodie", "men"],
    inStock: true
  },
  {
    id: "PROD-108",
    name: "Crisp Oxford Pure Cotton Shirt",
    category: "Men",
    subCategory: "Formal Wear",
    gender: "men",
    color: "White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    style: "Minimal",
    occasion: "Office",
    price: 1499,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1620012253295-c15c429f66bf?auto=format&fit=crop&w=600&q=80",
    material: "100% Giza Long-Staple Cotton",
    description: "Timeless white button-down with non-iron technology and mother-of-pearl buttons. Pairs seamlessly with suits or chinos.",
    tags: ["white", "minimal", "office", "formal", "shirt", "cotton"],
    inStock: true
  },
  {
    id: "PROD-109",
    name: "Kids Festive Royal Kurta Set",
    category: "Kids",
    subCategory: "Traditional Wear",
    gender: "kids",
    color: "Blue",
    sizes: ["XS", "S", "M", "L"],
    style: "Traditional",
    occasion: "Festival",
    price: 1299,
    originalPrice: 2199,
    rating: 4.9,
    reviewsCount: 65,
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=600&q=80",
    material: "Jacquard Silk Blend with Cotton Lining",
    description: "Vibrant ethnic kurta with embroidered nehru jacket and comfortable elasticated dhoti pants designed for joyful celebrations.",
    tags: ["blue", "traditional", "festival", "kids", "kurta", "wedding"],
    inStock: true
  },
  {
    id: "PROD-110",
    name: "Classic Slim Fit Black Trousers",
    category: "Formal Wear",
    subCategory: "Men",
    gender: "men",
    color: "Black",
    sizes: ["S", "M", "L", "XL", "XXL"],
    style: "Modern",
    occasion: "Wedding",
    price: 1799,
    originalPrice: 2999,
    rating: 4.8,
    reviewsCount: 180,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80",
    material: "Stretch Poly-Viscose Blend",
    description: "Tailored formal trousers with sharp pressed creases, shirt-gripper waistband, and slight taper at the hem.",
    tags: ["black", "modern", "wedding", "formal", "trousers", "office"],
    inStock: true
  },
  {
    id: "PROD-111",
    name: "Ruby Red Off-Shoulder Ballgown",
    category: "Women",
    subCategory: "Party Wear",
    gender: "women",
    color: "Red",
    sizes: ["XS", "S", "M", "L"],
    style: "Modern",
    occasion: "Party",
    price: 4299,
    originalPrice: 7499,
    rating: 4.9,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=600&q=80",
    material: "Duchess Satin",
    description: "Dramatic crimson evening gown with sweetheart corset bodice, internal boning, and sweeping dramatic train.",
    tags: ["red", "modern", "party", "wedding", "gown", "women"],
    inStock: true
  },
  {
    id: "PROD-112",
    name: "Sage Green Relaxed Cargo Joggers",
    category: "Casual Wear",
    subCategory: "Men",
    gender: "men",
    color: "Green",
    sizes: ["S", "M", "L", "XL"],
    style: "Streetwear",
    occasion: "College",
    price: 1399,
    originalPrice: 2499,
    rating: 4.7,
    reviewsCount: 94,
    image: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=600&q=80",
    material: "Cotton Twill with Mechanical Stretch",
    description: "Ergonomic modular streetwear cargo pants with snap utility pockets and adjustable ankle bungee cords.",
    tags: ["green", "streetwear", "college", "casual", "cargo", "men"],
    inStock: true
  },
  {
    id: "PROD-113",
    name: "Ivory Pearl Traditional Banarasi Saree",
    category: "Traditional Wear",
    subCategory: "Women",
    gender: "women",
    color: "White",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    style: "Traditional",
    occasion: "Wedding",
    price: 5499,
    originalPrice: 9999,
    rating: 5.0,
    reviewsCount: 178,
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80",
    material: "Pure Katan Silk with Silver Resham",
    description: "Handcrafted Banarasi heirloom weave with intricate floral jaal motifs and opulent contrast pallu.",
    tags: ["white", "traditional", "wedding", "saree", "silk", "women"],
    inStock: true
  },
  {
    id: "PROD-114",
    name: "Sky Blue Italian Cut Blazer & Vest",
    category: "Men",
    subCategory: "Party Wear",
    gender: "men",
    color: "Blue",
    sizes: ["M", "L", "XL"],
    style: "Modern",
    occasion: "Date",
    price: 4999,
    originalPrice: 8499,
    rating: 4.8,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80",
    material: "Linen-Silk Breathable Weave",
    description: "Contemporary tailored blue jacket with peak lapels, matching double-breasted vest, and satin lining.",
    tags: ["blue", "modern", "date", "party", "blazer", "men"],
    inStock: true
  },
  {
    id: "PROD-115",
    name: "Little Princess Rose Petal Tulle Frock",
    category: "Kids",
    subCategory: "Party Wear",
    gender: "kids",
    color: "Pink",
    sizes: ["XS", "S", "M"],
    style: "Modern",
    occasion: "Party",
    price: 1199,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 104,
    image: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=600&q=80",
    material: "Skin-Safe Organic Cotton Lining with Multi-layer Tulle",
    description: "Twirl-ready party dress with sparkling sequined yoke, fluffy tiered tutu skirt, and matching bow headband.",
    tags: ["pink", "party", "kids", "frock", "dress"],
    inStock: true
  },
  {
    id: "PROD-116",
    name: "Onyx Minimalist Oxford Derby Shoes",
    category: "Formal Wear",
    subCategory: "Men",
    gender: "men",
    color: "Black",
    sizes: ["S", "M", "L", "XL"],
    style: "Minimal",
    occasion: "Wedding",
    price: 2199,
    originalPrice: 3899,
    rating: 4.9,
    reviewsCount: 230,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=600&q=80",
    material: "Full Grain Italian Burnished Leather",
    description: "Sleek wholecut lace-up dress shoes with cushioned orthotic insole and durable Goodyear-welted rubber sole.",
    tags: ["black", "formal", "wedding", "shoes", "minimal", "men"],
    inStock: true
  },
  {
    id: "PROD-117",
    name: "Chic Cobalt Blue Satin Slip Dress",
    category: "Women",
    subCategory: "Party Wear",
    gender: "women",
    color: "Blue",
    sizes: ["XS", "S", "M", "L"],
    style: "Modern",
    occasion: "Date",
    price: 2299,
    originalPrice: 3999,
    rating: 4.7,
    reviewsCount: 145,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    material: "Heavyweight Liquid Satin",
    description: "Bias-cut 90s inspired cowl neckline midi dress that skims curves gracefully with adjustable spaghetti straps.",
    tags: ["blue", "modern", "date", "party", "dress", "satin"],
    inStock: true
  },
  {
    id: "PROD-118",
    name: "Minimalist Chrono All-Black Steel Watch",
    category: "Formal Wear",
    subCategory: "Men",
    gender: "unisex",
    color: "Black",
    sizes: ["M", "L"],
    style: "Minimal",
    occasion: "Wedding",
    price: 1899,
    originalPrice: 3499,
    rating: 4.8,
    reviewsCount: 195,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
    material: "316L Surgical Stainless Steel with Sapphire Crystal",
    description: "Ultra-thin 6.8mm profile analog timepiece with matte black dial, mesh strap, and 5ATM water resistance.",
    tags: ["black", "minimal", "watch", "wedding", "formal", "accessories"],
    inStock: true
  }
];

// Curated Category Definitions
const CATEGORY_ITEMS = [
  { id: "Men", name: "Men", icon: "👔", count: "86 Items", desc: "Suits, Shirts & Streetwear" },
  { id: "Women", name: "Women", icon: "👗", count: "114 Items", desc: "Dresses, Gowns & Sarees" },
  { id: "Kids", name: "Kids", icon: "🧒", count: "48 Items", desc: "Festive & Casual Outfits" },
  { id: "Party Wear", name: "Party Wear", icon: "🎉", count: "72 Items", desc: "Cocktail & Gala Attire" },
  { id: "Formal Wear", name: "Formal Wear", icon: "💼", count: "65 Items", desc: "Office & Executive Suits" },
  { id: "Traditional Wear", name: "Traditional Wear", icon: "🌸", count: "54 Items", desc: "Ethnic Kurtas & Silks" },
  { id: "Casual Wear", name: "Casual Wear", icon: "👕", count: "90 Items", desc: "Everyday Comfort & Tees" }
];

// System Architecture Data Models for Section 19 & 20
const SYSTEM_SCHEMA_MODELS = [
  {
    tableName: "Users",
    description: "Registered shoppers, preferences & body size profiles",
    fields: [
      { name: "user_id", type: "VARCHAR(36) PRIMARY KEY", desc: "UUID" },
      { name: "name", type: "VARCHAR(100)", desc: "Shopper Full Name" },
      { name: "email", type: "VARCHAR(255) UNIQUE", desc: "Login Email" },
      { name: "password", type: "VARCHAR(255)", desc: "Argon2 Hashed Hash" },
      { name: "preferences", type: "JSON", desc: "{style, colors, occasions}" },
      { name: "size", type: "VARCHAR(10)", desc: "Saved Default Fit (e.g. M)" }
    ]
  },
  {
    tableName: "Products",
    description: "Commercial garments with multidimensional attributes",
    fields: [
      { name: "product_id", type: "VARCHAR(36) PRIMARY KEY", desc: "SKU Identifier" },
      { name: "name", type: "VARCHAR(200)", desc: "Commercial Item Name" },
      { name: "category", type: "VARCHAR(50)", desc: "Top-level Category" },
      { name: "color", type: "VARCHAR(30)", desc: "Primary Garment Color" },
      { name: "size", type: "VARCHAR(50)", desc: "Comma-separated sizes" },
      { name: "style", type: "VARCHAR(50)", desc: "Fashion Style Archetype" },
      { name: "occasion", type: "VARCHAR(50)", desc: "Target Social Occasion" },
      { name: "price", type: "DECIMAL(10,2)", desc: "Retail Price in INR" },
      { name: "rating", type: "DECIMAL(2,1)", desc: "Customer Rating 1-5" },
      { name: "image", type: "TEXT", desc: "High-Res Image CDN URL" }
    ]
  },
  {
    tableName: "Orders",
    description: "Transaction records, customer delivery & payment states",
    fields: [
      { name: "order_id", type: "VARCHAR(36) PRIMARY KEY", desc: "e.g. #AI2026001" },
      { name: "user_id", type: "VARCHAR(36) FOREIGN KEY", desc: "References Users" },
      { name: "products", type: "JSON", desc: "Array of cart items & prices" },
      { name: "quantity", type: "INT", desc: "Total Garments in Order" },
      { name: "total_price", type: "DECIMAL(10,2)", desc: "Grand Total Invoiced" },
      { name: "status", type: "VARCHAR(30)", desc: "Placed, Confirmed, Shipped, Delivered" }
    ]
  },
  {
    tableName: "Recommendations",
    description: "AI scoring logs & personal recommendation matches",
    fields: [
      { name: "recommendation_id", type: "VARCHAR(36) PRIMARY KEY", desc: "UUID" },
      { name: "user_id", type: "VARCHAR(36) FOREIGN KEY", desc: "Target Shopper" },
      { name: "product_id", type: "VARCHAR(36) FOREIGN KEY", desc: "Recommended SKU" },
      { name: "matching_score", type: "INT", desc: "Computed Match % (e.g. 92%)" }
    ]
  }
];

// Color Theory Knowledge Base for Section 9
const COLOR_THEORY_PALETTES = {
  "fair": {
    name: "Fair Complexion",
    recommended: [
      { name: "Navy Blue", hex: "#1e3a8a" },
      { name: "Emerald Green", hex: "#065f46" },
      { name: "Burgundy", hex: "#831843" },
      { name: "Dusty Rose", hex: "#f472b6" }
    ],
    advice: "Rich jewel tones and deep contrast colors complement porcelain and fair undertones."
  },
  "medium": {
    name: "Medium / Wheatish",
    recommended: [
      { name: "Royal Blue", hex: "#2563eb" },
      { name: "Crimson Red", hex: "#dc2626" },
      { name: "Mustard Gold", hex: "#d97706" },
      { name: "Classic Black", hex: "#0f172a" }
    ],
    advice: "Warm metallics, vibrant saturated primaries, and rich blacks accentuate medium warm undertones."
  },
  "olive": {
    name: "Olive Complexion",
    recommended: [
      { name: "Sage Green", hex: "#047857" },
      { name: "Warm Burgundy", hex: "#991b1b" },
      { name: "Plum Purple", hex: "#7c3aed" },
      { name: "Cream White", hex: "#f8fafc" }
    ],
    advice: "Earthy greens, regal plums, and creamy ivory harmoniously elevate olive skin tones."
  },
  "deep": {
    name: "Deep Complexion",
    recommended: [
      { name: "Electric Blue", hex: "#0284c7" },
      { name: "Pure White", hex: "#ffffff" },
      { name: "Vivid Fuchsia", hex: "#ec4899" },
      { name: "Golden Yellow", hex: "#f59e0b" }
    ],
    advice: "High-contrast brights, crisp whites, and bold luminous jewel tones glow strikingly on deep skin."
  }
};
